#error Parsing error near 'Feature: ConnexionDesJoueurs'
#error Parsing error near 'In order to avoid silly mistakes'
#error Parsing error near 'As a math idiot'
#error Parsing error near 'I want to be told the sum of two numbers'
#error Parsing error near 'Scenario: Add two numbers'
#error Parsing error near 'Given I have entered 50 into the calculator'