// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace LoupGarou.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PeuplerLeVillageFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PeuplerLeVillage.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("fr-FR"), "Peupler Le Village", "Dans le but de jouer avec des copains\r\nEn tant que joueur\r\nJe veux créer un villa" +
                    "ge", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Peupler Le Village")))
            {
                LoupGarou.Specs.Features.PeuplerLeVillageFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("le jeu du loup garou", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Soit ");
#line 8
 testRunner.And("un maitre du jeu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Création du village")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Peupler Le Village")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Village")]
        public virtual void CreationDuVillage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Création du village", new string[] {
                        "Village"});
#line 11
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 12
 testRunner.Given("8 habitants sont attendus", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Soit ");
#line 13
 testRunner.And("Il y a déjà 7 habitants dans le village", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line 14
 testRunner.When("le 8em habitant arrive", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Lorsque ");
#line 15
 testRunner.Then("le maitre du jeu indique que tous les habitants sont présents", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line 16
 testRunner.And("le jeu peut commencer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Un habitant emménage dans le village")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Peupler Le Village")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Village")]
        public virtual void UnHabitantEmmenageDansLeVillage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Un habitant emménage dans le village", new string[] {
                        "Village"});
#line 19
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 20
 testRunner.Given("le migrant Ambroise", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Soit ");
#line 21
 testRunner.When("il emmenage dans le village", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Lorsqu\'");
#line 22
 testRunner.Then("Ambroise est un habitant du village", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line 23
 testRunner.And("le maitre du jeu salut Ambroise", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Attribution des rôles aux habitants du village")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Peupler Le Village")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Village")]
        public virtual void AttributionDesRolesAuxHabitantsDuVillage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Attribution des rôles aux habitants du village", new string[] {
                        "Village"});
#line 26
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 27
 testRunner.Given("un village simplifiée", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Soit ");
#line 28
 testRunner.And("il est peuplé de ses habitants", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line 29
 testRunner.When("le village est crée", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Lorsque ");
#line 30
 testRunner.Then("chaque habitant se retrouve avec un role", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line 31
 testRunner.And("le maitre du jeu pose le decor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
