// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace LoupGarou.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class RoleDeLaSorciereFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RoleDeLaSorciere.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("fr-FR"), "Rôle de la Sorcière", "Dans le but protéger le village\r\nEn tant que sorcière\r\nJe veux utiliser mes potio" +
                    "ns pour empoisonner ou sauver une personne qui vient d\'être dévorer", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Rôle de la Sorcière")))
            {
                LoupGarou.Specs.Features.RoleDeLaSorciereFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("le jeu du loup garou", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Soit ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Découverte de la victime des loups")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Rôle de la Sorcière")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("sorcière")]
        public virtual void DecouverteDeLaVictimeDesLoups()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Découverte de la victime des loups", new string[] {
                        "sorcière"});
#line 10
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 11
 testRunner.Given("Johanna est la sorcière", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Soit ");
#line 12
 testRunner.When("les loups ont choisit Ambroise", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quand ");
#line 13
 testRunner.Then("elle découvre que la victime est Ambroise", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Présentation de la sorcière")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Rôle de la Sorcière")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("sorcière")]
        public virtual void PresentationDeLaSorciere()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Présentation de la sorcière", new string[] {
                        "sorcière"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 24
 testRunner.Given("Johanna est la sorcière", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Soit ");
#line 25
 testRunner.When("le personnage de la sorcière est attribué à Johanna", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Lorsque ");
#line 26
 testRunner.Then("Johanna est une villageoise", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line 27
 testRunner.And("Johanna est la sorcière", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Fin du tour de la sorcière")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Rôle de la Sorcière")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("sorcière")]
        public virtual void FinDuTourDeLaSorciere()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Fin du tour de la sorcière", new string[] {
                        "sorcière"});
#line 31
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 32
 testRunner.Given("Johanna jouant le personnage de Sorcière", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Soit ");
#line 33
 testRunner.And("son tour est en cours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line 34
 testRunner.When("qu\'elle valide l\'utilisation de ses potions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Lorsque ");
#line 35
 testRunner.Then("le maître du jeu rendort la sorcière", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("tour de la sorcière")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Rôle de la Sorcière")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("sorcière")]
        public virtual void TourDeLaSorciere()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("tour de la sorcière", new string[] {
                        "sorcière"});
#line 38
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 39
 testRunner.Given("Johanna jouant le personnage de Sorcière", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Soit ");
#line 40
 testRunner.And("la victime des loups est le joueur Ambroise", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line 41
 testRunner.When("son tour est en cours", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Lorsque ");
#line 42
 testRunner.Then("elle découvre que la victime est Ambroise", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("utilisation de la potion de vie")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Rôle de la Sorcière")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("sorcière")]
        public virtual void UtilisationDeLaPotionDeVie()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("utilisation de la potion de vie", new string[] {
                        "sorcière"});
#line 45
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 46
 testRunner.Given("Johanna jouant le personnage de Sorcière", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Soit ");
#line 47
 testRunner.And("la victime des loups est le joueur Ambroise", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line 48
 testRunner.When("qu\'elle utilise sa potion de vie", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Lorsque ");
#line 49
 testRunner.Then("Ambroise n\'est pas mort au prochain levé du soleil", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line 50
 testRunner.And("la sorcière n\'a plus de potion de mort", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("utilisation de la potion de mort")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Rôle de la Sorcière")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("sorcière")]
        public virtual void UtilisationDeLaPotionDeMort()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("utilisation de la potion de mort", new string[] {
                        "sorcière"});
#line 53
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 54
 testRunner.Given("Johanna jouant le personnage de Sorcière", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Soit ");
#line 55
 testRunner.And("Ambroise un joueur encore en vie", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line 56
 testRunner.When("qu\'elle utilise sa potion de mort sur Ambroise", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Lorsque ");
#line 57
 testRunner.Then("Ambroise est mort au prochain levé du soleil", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line 58
 testRunner.And("la sorcière n\'a plus de potion de mort", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
