//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoupGarou.Core.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoupGarou.Core.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre rôle est .
        /// </summary>
        public static string AnnonceRoleDuJoueur {
            get {
                return ResourceManager.GetString("AnnonceRoleDuJoueur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le village se réveille..
        /// </summary>
        public static string DebutTourVillageois {
            get {
                return ResourceManager.GetString("DebutTourVillageois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Et les habitants découvrent avec effroi le corps de {0}, un {1}, sans vie..
        /// </summary>
        public static string DecouverteDuCorps {
            get {
                return ResourceManager.GetString("DecouverteDuCorps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;il se fait dévorer par les Loups-Garous ou éliminé malencontreusement par les villageois, le Chasseur doit répliquer avant de rendre l&apos;âme, en éliminant immédiatement n&apos;importe quel autre joueur de son choix. Cas particulier: Le chasseur est l&apos;amoureux d&apos;un joueur éliminé, avant de quitter la partie le chasseur doit immédiatement éliminer un autre joueur de son choix. cela peut entraîner une partie où il ne reste aucun joueur survivant. Dans ce cas la victoire n&apos;appartient à aucun des camps..
        /// </summary>
        public static string DescriptionRoleChasseur {
            get {
                return ResourceManager.GetString("DescriptionRoleChasseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cupidon, appelé la première nuit. En décochant ses flèches magiques, Cupidon a le pouvoir de rendre deux personnes amoureuses à jamais. La première nuit (tour préliminaire), il désigne les deux joueurs (ou joueuses) amoureux. Cupidon peut, s&apos;il le veut, se désigner comme l&apos;un des deux Amoureux. Si l&apos;un des Amoureux est éliminé, l&apos;autre meurt de chagin immédiatement. Un amoureux ne doit jamais éliminer son aimé, ni lui porter préjudice (même pour faire semblant!). Attention: si l&apos;un des amoureux est un villa [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string DescriptionRoleCupidon {
            get {
                return ResourceManager.GetString("DescriptionRoleCupidon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chaque nuit, ils dévorent un villeagois. Le jour, ils essaient de masquer leur identité nocturne pour échapper à la vindicte populaire. En aucun cas un Loup-Garou peut dévorer un Loup-Garou..
        /// </summary>
        public static string DescriptionRoleLoupGarou {
            get {
                return ResourceManager.GetString("DescriptionRoleLoupGarou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La petite fille peut, en entrouvant les yeux, espionner les Loups-Garous pendant leur réviel. Si elle se fait surprendre par un des Loups-Garous, elle pourra être dévorée immédiatement (en silence), à la place de la victime désignée. La petite fille ne peut espionner que la nuit, durant le tour d&apos;éveil des Loups-Garous. Elle n&apos;a pas le droit de se faire passer pour un Loup-Garou et d&apos;ouvrir grand les yeux..
        /// </summary>
        public static string DescriptionrolePetiteFille {
            get {
                return ResourceManager.GetString("DescriptionrolePetiteFille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La sorcière, appelée la nuit. Elle sait concocter deux potion extrêment puissantes: une potion de guérison pour ressuciter le joueur dévoré par les Loups-Garous, une potion d&apos;empoisonnement, utilisée la nuit pour éliminer un joueur. La sorcière doit utiliser chaque potion une seule fois dans la partie. ELle peut se servir de ses deux potions la même nuit. Le matin, suivant la ou les potions utilisées, il pourra y avoir deux joueurs éliminés ou aucun! La sorcière peut également utiliser la potion de guérison [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string DescriptionRoleSorciere {
            get {
                return ResourceManager.GetString("DescriptionRoleSorciere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le simple villageois. Il n&apos;a aucune compétance particulière. Ses seules armes sont la capacité d&apos;analyse des comportements pour identifier les Loups-Garous, et la force de conviction pour empêcher l&apos;exécution de l&apos;innocent qu&apos;il est..
        /// </summary>
        public static string DescriptionRoleVillageois {
            get {
                return ResourceManager.GetString("DescriptionRoleVillageois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La voyante, appelée la nuit. Chaque nuit, elle voit la carte d&apos;un joueur de son choix. Elle doit aider les autres villageois mais rester discrète pour ne pas être demasquée par les Loups-Garous..
        /// </summary>
        public static string DescriptionRoleVoyante {
            get {
                return ResourceManager.GetString("DescriptionRoleVoyante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les loups garous se rendorment..
        /// </summary>
        public static string FinTourLoupGarou {
            get {
                return ResourceManager.GetString("FinTourLoupGarou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le village se rendort..
        /// </summary>
        public static string FinTourVillageois {
            get {
                return ResourceManager.GetString("FinTourVillageois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La voyante se rendort..
        /// </summary>
        public static string FinTourVoyante {
            get {
                return ResourceManager.GetString("FinTourVoyante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les villageois ont donc jugé {0} coupable, un {1}..
        /// </summary>
        public static string LynchageVillageois {
            get {
                return ResourceManager.GetString("LynchageVillageois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à chasseur.
        /// </summary>
        public static string NomRoleChasseur {
            get {
                return ResourceManager.GetString("NomRoleChasseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cupidon.
        /// </summary>
        public static string NomRoleCupidon {
            get {
                return ResourceManager.GetString("NomRoleCupidon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à loup-garou.
        /// </summary>
        public static string NomRoleLoupGarou {
            get {
                return ResourceManager.GetString("NomRoleLoupGarou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à petite fille.
        /// </summary>
        public static string NomRolePetiteFille {
            get {
                return ResourceManager.GetString("NomRolePetiteFille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à sorcière.
        /// </summary>
        public static string NomRoleSorciere {
            get {
                return ResourceManager.GetString("NomRoleSorciere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à villageois.
        /// </summary>
        public static string NomRoleVillageois {
            get {
                return ResourceManager.GetString("NomRoleVillageois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à voyante.
        /// </summary>
        public static string NomRoleVoyante {
            get {
                return ResourceManager.GetString("NomRoleVoyante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Au trés fond d&apos;un forêt, à flan de montagne, un petit village est depuis peu devenu la proie de Loups Garous. Des meurtres ignobles sont commis chaque nuit par certains habitants du village, devenus Lycanthropes à cause d&apos;un phénomène mystérieux... Les villageois doivent se ressaisir pour éradiquer ce nouveau fléau venu du fons des âges, avant que le village ne perde ses derniers habitants..
        /// </summary>
        public static string PresentationDuJeu {
            get {
                return ResourceManager.GetString("PresentationDuJeu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue dans notre village.
        /// </summary>
        public static string SalutationHabitant {
            get {
                return ResourceManager.GetString("SalutationHabitant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le village est complet nous allons pouvoir commencer.
        /// </summary>
        public static string VillageComplet {
            get {
                return ResourceManager.GetString("VillageComplet", resourceCulture);
            }
        }
    }
}
